### ISSUE TITLE
Pip Install doesnt work 

### ISSUE THREAD

**Issue by sathik11** [brendano/stanford_corenlp_pywrapper#11]
Pip install stanford_corenlp_pywrapper throws "Couldnot find download that satisfy requirement"

PIP LOG:
==============
C:\python27\Scripts\pip run on 12/10/14 17:01:19
Downloading/unpacking stanford-corenlp-pywrapper
  Getting page https://pypi.python.org/simple/stanford_corenlp_pywrapper/
  Could not fetch URL https://pypi.python.org/simple/stanford_corenlp_pywrapper/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/stanford_corenlp_pywrapper/ when looking for download links for stanford-corenlp-pywrapper
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for stanford-corenlp-pywrapper:
  * https://pypi.python.org/simple/stanford_corenlp_pywrapper/
  Getting page https://pypi.python.org/simple/stanford_corenlp_pywrapper/
  Could not fetch URL https://pypi.python.org/simple/stanford_corenlp_pywrapper/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/stanford_corenlp_pywrapper/ when looking for download links for stanford-corenlp-pywrapper
  Could not find any downloads that satisfy the requirement stanford-corenlp-pywrapper
Cleaning up...
  Removing temporary dir c:\users\sathik\appdata\local\temp\pip_build_Sathik...
No distributions at all found for stanford-corenlp-pywrapper
Exception information:

**Comment by brendano** [comment]
i merged a PR about this. does this still occur?

**Comment by brendano** [comment]
closing unless we confirm this still occurs
