### ISSUE TITLE
question/wishlist Get the root relation from the dependency parse

### ISSUE THREAD

**Issue by sandeepsoni** [brendano/stanford_corenlp_pywrapper#13]
Is it possible to obtain the root relation in the dependency parse using the wrapper just like the one described in the manual or in the online demo? In the fullparse mode, I don't see the root relation.

If there is no support, is it worthwhile to add it?

**Comment by brendano** [comment]
that's weird, it should be there.  it's definitely a bug that it's not there.

**Comment by sandeepsoni** [comment]
Apparently, the root is not stored in the semantic graph. And an explanation is [here](http://stackoverflow.com/questions/16300056/stanford-core-nlp-missing-roots). As per the suggestion there, I can get the root relation by calling a separate function. 

If it makes sense to have the root relation in the python socket wrapper output, I could raise a pull request.

**Comment by brendano** [comment]
sure. make sure to link to that discussion.  if they change their system then it's no use doing the workaround here.  i wont have time to implement this anytime soon anyway, unless someone else want to.
