### ISSUE TITLE
Socket error loading NER annotator

### ISSUE THREAD

**Issue by rlvoyer** [brendano/stanford_corenlp_pywrapper#17]
Hi there. Any idea what would be causing this:

```python
In [4]: p=sockwrap.SockWrap("ner",corenlp_jars=["/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar","/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar"])
INFO:StanfordSocketWrap:Starting pipe subprocess, and waiting for signal it's ready, with command:  exec java -Xmx4g -cp '/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/piperunner.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/guava-13.0.1.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/jackson-all-1.9.11.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar'     corenlp.PipeCommandRunner --server 12340  --mode ner
[Server] Using prebaked mode type: ner
[Server] Using output types: [pos, lemmas, ner, normner]
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [2.4 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... INFO:StanfordSocketWrap:socket error when making connection ([Errno 61] Connection refused)
INFO:StanfordSocketWrap:pausing before retry
```

Thanks for your help!

**Comment by brendano** [comment]
It's still loading the models and these messages are usually normal. What
happens after this?

On Friday, February 20, 2015, Robert Voyer <notifications@github.com> wrote:

> Hi there. Any idea what would be causing this:
>
> In [4]: p=sockwrap.SockWrap("ner",corenlp_jars=["/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar","/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar"])
> INFO:StanfordSocketWrap:Starting pipe subprocess, and waiting for signal it's ready, with command:  exec java -Xmx4g -cp '/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/piperunner.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/
>  lib/guava-13.0.1.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/jackson-all-1.9.11.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar'     corenlp.PipeCommandRunner --server 12340  --mode ner
> [Server] Using prebaked mode type: ner
> [Server] Using output types: [pos, lemmas, ner, normner]
> Adding annotator tokenize
> TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
> Adding annotator ssplit
> Adding annotator pos
> Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [2.4 sec].
> Adding annotator lemma
> Adding annotator ner
> Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... INFO:StanfordSocketWrap:socket error when making connection ([Errno 61] Connection refused)
> INFO:StanfordSocketWrap:pausing before retry
>
> Thanks for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brendano/stanford_corenlp_pywrapper/issues/17>.
>


-- 
-brendan [mobile]

**Comment by rlvoyer** [comment]
Hmm... I was afraid that maybe I wasn't patient enough, but it seems to be doing this forever:

```python
INFO:StanfordSocketWrap:socket error when making connection ([Errno 22] Invalid argument)
INFO:StanfordSocketWrap:pausing before retry
```

**Comment by rlvoyer** [comment]
It appears to behave normally if I stick to POS tagging, but I don't think it's recovering correctly from the timeout in the case of models that take a while to load:

```python
In [4]: p=sockwrap.SockWrap("pos",corenlp_jars=["/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar","/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar"])
INFO:StanfordSocketWrap:Starting pipe subprocess, and waiting for signal it's ready, with command:  exec java -Xmx4g -cp '/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/piperunner.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/guava-13.0.1.jar:/Users/rlvoyer/Envs/glc_pypi_1.3/lib/python2.7/site-packages/stanford_corenlp_pywrapper/lib/jackson-all-1.9.11.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar:/Users/rlvoyer/Code/stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar'     corenlp.PipeCommandRunner --server 12340  --mode pos
[Server] Using prebaked mode type: pos
[Server] Using output types: [pos, lemmas]
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.6 sec].
Adding annotator lemma
[Server] Started socket server on port 12340

INFO:StanfordSocketWrap:Successful ping. The server has started.
INFO:StanfordSocketWrap:Subprocess is ready.
```

**Comment by brendano** [comment]
something is wrong. i dont know what. please provide more details like os
and python versionwhat code youre running.

On Friday, February 20, 2015, Robert Voyer <notifications@github.com> wrote:

> Hmm... I was afraid that maybe I wasn't patient enough, but it seems to be
> doing this forever:
>
> INFO:StanfordSocketWrap:socket error when making connection ([Errno 22] Invalid argument)
> INFO:StanfordSocketWrap:pausing before retry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brendano/stanford_corenlp_pywrapper/issues/17#issuecomment-75339297>
> .
>


-- 
-brendan [mobile]

**Comment by rlvoyer** [comment]
OS: OS X 10.10.2
Python version: 2.7.6
Java version: "1.8.0_31"

What other details would be useful to know?

**Comment by rlvoyer** [comment]
As a workaround, I made some changes to the sockwrap module to only startup the server if requested. This way, I was able to startup the server manually and then use the client code to connect to (but not relaunch) the server.

**Comment by brendano** [comment]
i saw this error too and this change seems to fix...
