### ISSUE TITLE
/bin/sh: 1: exec: java: not found

### ISSUE THREAD

**Issue by thavasimaniraj** [brendano/stanford_corenlp_pywrapper#39]
When i am trying to run this source code from python in ubuntu, there are giving this error:

>>> proc = CoreNLP("pos", corenlp_jars=["/home/jeyam/Desktop/stanford-corenlp-full-2015-04-20/*"])
INFO:CoreNLP_PyWrapper:mode given as 'pos' so setting annotators: tokenize, ssplit, pos, lemma
INFO:CoreNLP_PyWrapper:Starting java subprocess, and waiting for signal it's ready, with command: exec java -Xmx4g -XX:ParallelGCThreads=1 -cp '/home/jeyam/stanford_corenlp_pywrapper/stanford_corenlp_pywrapper/lib/*:/home/jeyam/Desktop/stanford-corenlp-full-2015-04-20/*'      corenlp.SocketServer --outpipe /tmp/corenlp_pywrap_pipe_pypid=3106_time=1487060888.04  --configdict '{"annotators": "tokenize, ssplit, pos, lemma"}'
/bin/sh: 1: exec: java: not found
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stanford_corenlp_pywrapper/sockwrap.py", line 151, in __init__
    self.start_server()
  File "stanford_corenlp_pywrapper/sockwrap.py", line 181, in start_server
    self.outpipe_fp = open(self.outpipe, 'r')
KeyboardInterrupt
>>> 

Can you help me, how to solve it.

**Comment by brendano** [comment]
You don't have java installed.

**Comment by thavasimaniraj** [comment]
Dear sir,

Thank you for your reply.

I resolved that problem by installing java PATH. Now other kind of
error show due to invalid heap size like:

jeyam@ubuntu:~$ cd stanford_corenlp_pywrapper/
jeyam@ubuntu:~/stanford_corenlp_pywrapper$ python
Python 2.7.3 (default, Apr 20 2012, 22:44:07)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from stanford_corenlp_pywrapper import CoreNLP
>>> proc = CoreNLP("pos", corenlp_jars=["/home/jeyam/Desktop/stanford-corenlp-full-2015-04-20/*"])
INFO:CoreNLP_PyWrapper:mode given as 'pos' so setting annotators:
tokenize, ssplit, pos, lemma
INFO:CoreNLP_PyWrapper:Starting java subprocess, and waiting for
signal it's ready, with command: exec java -Xmx4g
-XX:ParallelGCThreads=1 -cp
'/home/jeyam/stanford_corenlp_pywrapper/stanford_corenlp_pywrapper/lib/*:/home/jeyam/Desktop/stanford-corenlp-full-2015-04-20/*'
     corenlp.SocketServer --outpipe
/tmp/corenlp_pywrap_pipe_pypid=4078_time=1487085095.42  --configdict
'{"annotators": "tokenize, ssplit, pos, lemma"}'
Invalid maximum heap size: -Xmx4g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


I am using ubuntu 32 bit OS within VMWare and my RAM size is 4 GB. Can
you please guide me What configuration did you use?

On 2/14/17, brendano <notifications@github.com> wrote:
> You don't have java installed.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/brendano/stanford_corenlp_pywrapper/issues/39#issuecomment-279706911


-- 
Regards with,

J.Manimaran M.Sc.,
